[phases.setup]
nixPkgs = [
  "php83",
  "php83Packages.composer",
  "php83Extensions.pdo_pgsql",
  "php83Extensions.sqlite3",
  "nodejs_20"
]

[phases.install]
commands = [
  "if [ -n \"$FLUX_COMPOSER_EMAIL\" ] && [ -n \"$FLUX_COMPOSER_KEY\" ]; then composer global config --auth http-basic.composer.fluxui.dev $FLUX_COMPOSER_EMAIL $FLUX_COMPOSER_KEY; fi",
  "composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader",
  "npm install"
]

[phases.build]
commands = [
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
command = "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host 0.0.0.0 --port $PORT"
