[build]
builder = "nixpacks"
nixpacksConfigPath = "./nixpacks.toml"

[deploy]
startCommand = "php artisan serve --host 0.0.0.0 --port $PORT"
preDeployCommand = "php artisan migrate --force"
restartPolicyType = "on_failure"
